version: '3'
services:
  flask:
    build:
      context: Dockerfiles
      dockerfile: ./app/Dockerfile
    container_name: flask
    ports:
      - 4000:4000
    environment:
      SECRET_KEY: pavan
      MONGODB_HOSTNAME: mongodb
    depends_on:
      - mongodb
    networks:
      - backend
  mongodb:
    image: mongo:4.0.8
    container_name: mongodb
    ports:
      - 27017:27017
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - backend
networks:
  backend:
    driver: bridge